### ISSUE TITLE
Fix: defining `template_params` cause Exception

### ISSUE THREAD

**Issue by mtache** [arista-netdevops-community/anta#227]
`template_params` works only when defined as a list.
The loader code raises an Exception when this is a dict (which is coherent with the way test parameters are defined).

This works:
```
anta.tests.stp:
  - VerifySTPMode:
      mode: mstp
      template_params:
        - vlan: 100
```

This does not work:
```
anta.tests.stp:
  - VerifySTPMode:
      mode: mstp
      template_params:
        vlan: 100
```

Traceback:
```
Traceback (most recent call last):
  File "/home/mtache/.pyenv/versions/anta/bin/anta", line 8, in <module>
    sys.exit(cli())
  File "/mnt/lab/projects/anta/anta/cli/cli.py", line 87, in cli
    anta(obj={}, auto_envvar_prefix="ANTA")
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/lab/projects/anta/anta/cli/check/commands.py", line 53, in table
    results = check_run(
  File "/mnt/lab/projects/anta/anta/cli/check/utils.py", line 52, in check_run
    asyncio.run(main(results, inventory_anta, tests_catalog, tags=tags), debug=False)
  File "/home/mtache/.pyenv/versions/3.9.16/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/mtache/.pyenv/versions/3.9.16/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/lab/projects/anta/anta/runner.py", line 55, in main
    coros.append(test[0](device=device, template_params=template_params).test(eos_data=None, **test_params))
  File "/mnt/lab/projects/anta/anta/models.py", line 139, in __init__
    self.instance_commands.extend(
  File "/mnt/lab/projects/anta/anta/models.py", line 141, in <genexpr>
    command=tpl.template.format(**param),
TypeError: str.format() argument after ** must be a mapping, not str
```

**Comment by carl-baillargeon** [comment]
We should also support different input formats for `template_params`.  For VLANs, it would be nice to be able to enter:

```
template_params:
  vlans: "2-4094"
```
We could also add something like:
```
template_params:
  vlans: "10,20-100"
```
Same goes for tests with VRFs.

Thanks
