### ISSUE TITLE
Pydantic 2.0+ changed the constr() argument from regex to pattern breaking package v0.5.0

### ISSUE THREAD

**Issue by colinmacgiolla** [arista-netdevops-community/anta#252]
There was a breaking change in pydantic (https://github.com/pydantic/pydantic/blob/v2.0/pydantic/types.py#L266) which changed the `regex` argument in the `constr()` to `pattern`.

This causes the following error:
```
Traceback (most recent call last):
  File "/home/colin/anta/.venv/bin/anta", line 5, in <module>
    from anta.cli.cli import cli
  File "/home/colin/anta/.venv/lib/python3.10/site-packages/anta/cli/cli.py", line 12, in <module>
    from anta.cli.check import commands as check_commands
  File "/home/colin/anta/.venv/lib/python3.10/site-packages/anta/cli/check/commands.py", line 17, in <module>
    from .utils import check_run, display_json, display_table
  File "/home/colin/anta/.venv/lib/python3.10/site-packages/anta/cli/check/utils.py", line 19, in <module>
    from anta.inventory import AntaInventory
  File "/home/colin/anta/.venv/lib/python3.10/site-packages/anta/inventory/__init__.py", line 17, in <module>
    from .models import AntaInventoryInput, InventoryDevice, InventoryDevices
  File "/home/colin/anta/.venv/lib/python3.10/site-packages/anta/inventory/models.py", line 22, in <module>
    class AntaInventoryHost(BaseModel):
  File "/home/colin/anta/.venv/lib/python3.10/site-packages/anta/inventory/models.py", line 34, in AntaInventoryHost
    host: Union[constr(regex=RFC_1123_REGEX), IPvAnyAddress]  # type: ignore
TypeError: constr() got an unexpected keyword argument 'regex'
```

The problem is that we currently pin the pydantic requirements to `>=1.9.1`, so when pip installs pydantic 2.0.2 ANTA is broken.

We should either pin the requirements to `<2.0` [here](https://github.com/arista-netdevops-community/anta/blob/35cb549d5e0a299de80b937666e916cfee342652/pyproject.toml#L27) or else update [here](https://github.com/arista-netdevops-community/anta/blob/35cb549d5e0a299de80b937666e916cfee342652/anta/inventory/models.py#L34) to use `pattern`, and bump the requirements to be `>=2.0`.

Right now the v0.5.0 package is unusable without manually downgraging `pydantic`.

**Comment by mtache** [comment]
Well... this has been fixed in master :)
Let's release this quick !

**Comment by mtache** [comment]
Please try 0.6.0 on PyPi !
