### ISSUE TITLE
Cryptic error when VRF does not exist for cnnectivity test

### ISSUE THREAD

**Issue by gmuloc** [arista-netdevops-community/anta#392]
```
anta debug run-cmd -d leaf2 -c "ping vrf MGMT 1.1.1.1 source Management0 repeat 2"                      

Run command ping vrf MGMT 1.1.1.1 source Management0 repeat 2 on leaf2
[16:27:44] CRITICAL Command 'ping vrf MGMT 1.1.1.1 source Management0 repeat 2' failed on leaf2: EapiCommandError (CLI command 1 of 1 'ping vrf MGMT 1.1.1.1 source Management0 repeat 2' failed: could not run command)                                              misc.py:40
Traceback (most recent call last):
  File "/Users/guillaumemulocher/.pyenv/versions/anta/bin/anta", line 8, in <module>
    sys.exit(cli())
  File "/Users/guillaumemulocher/Github/gmuloc/anta/anta/cli/__init__.py", line 204, in cli
    anta(obj={}, auto_envvar_prefix="ANTA")  # pragma: no cover
  File "/Users/guillaumemulocher/.pyenv/versions/3.8.13/envs/anta/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/guillaumemulocher/.pyenv/versions/3.8.13/envs/anta/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/guillaumemulocher/.pyenv/versions/3.8.13/envs/anta/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/guillaumemulocher/.pyenv/versions/3.8.13/envs/anta/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/guillaumemulocher/.pyenv/versions/3.8.13/envs/anta/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/guillaumemulocher/.pyenv/versions/3.8.13/envs/anta/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/guillaumemulocher/Github/gmuloc/anta/anta/cli/debug/commands.py", line 53, in run_cmd
    console.print(c.json_output)
  File "/Users/guillaumemulocher/Github/gmuloc/anta/anta/models.py", line 113, in json_output
    raise RuntimeError(f"There is no output for command {self.command}")
RuntimeError: There is no output for command ping vrf MGMT 1.1.1.1 source Management0 repeat 2
```

**Comment by gmuloc** [comment]
current debug commands do not handle failed commands.
