### ISSUE TITLE
Ubuntu - anta installation from git fails on crypto lib

### ISSUE THREAD

**Issue by gmuloc** [arista-netdevops-community/anta#395]
```
➜  anta git:(main) anta --version
Traceback (most recent call last):
  File "/home/arista/.local/bin/anta", line 5, in <module>
    from anta.cli import cli
  File "/home/arista/git_projects/anta/anta/cli/__init__.py", line 18, in <module>
    from anta.cli.debug import commands as debug_commands
  File "/home/arista/git_projects/anta/anta/cli/debug/commands.py", line 18, in <module>
    from anta.device import AntaDevice
  File "/home/arista/git_projects/anta/anta/device.py", line 16, in <module>
    import asyncssh
  File "/home/arista/.local/lib/python3.10/site-packages/asyncssh/__init__.py", line 31, in <module>
    from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
  File "/home/arista/.local/lib/python3.10/site-packages/asyncssh/agent.py", line 34, in <module>
    from .public_key import KeyPairListArg, SSHCertificate, SSHKeyPair
  File "/home/arista/.local/lib/python3.10/site-packages/asyncssh/public_key.py", line 35, in <module>
    from .crypto import ed25519_available, ed448_available
  File "/home/arista/.local/lib/python3.10/site-packages/asyncssh/crypto/__init__.py", line 58, in <module>
    from .x509 import X509Certificate, X509Name, X509NamePattern
  File "/home/arista/.local/lib/python3.10/site-packages/asyncssh/crypto/x509.py", line 32, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

```
➜  anta git:(main) uname -a
Linux avd-clab 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
➜  anta git:(main) python3 --version
Python 3.10.12
```

**Comment by gmuloc** [comment]
https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openssl

```
➜  anta git:(main) pip install -U pyopenssl
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyopenssl in /usr/lib/python3/dist-packages (21.0.0)
Collecting pyopenssl
  Obtaining dependency information for pyopenssl from https://files.pythonhosted.org/packages/f0/e2/f8b4f1c67933a4907e52228241f4bd52169f3196b70af04403b29c63238a/pyOpenSSL-23.2.0-py3-none-any.whl.metadata
  Downloading pyOpenSSL-23.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: cryptography!=40.0.0,!=40.0.1,<42,>=38.0.0 in /home/arista/.local/lib/python3.10/site-packages (from pyopenssl) (41.0.3)
Requirement already satisfied: cffi>=1.12 in /home/arista/.local/lib/python3.10/site-packages (from cryptography!=40.0.0,!=40.0.1,<42,>=38.0.0->pyopenssl) (1.15.1)
Requirement already satisfied: pycparser in /home/arista/.local/lib/python3.10/site-packages (from cffi>=1.12->cryptography!=40.0.0,!=40.0.1,<42,>=38.0.0->pyopenssl) (2.21)
Downloading pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 1.8 MB/s eta 0:00:00
Installing collected packages: pyopenssl
Successfully installed pyopenssl-23.2.0
```

fixes it
